{% set name = "pythonfmu3" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/StephenSmith25/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c37e50e51e6f23ea9eeaaeee3f3b6a5674f129fa47674f0fa8efe820141e4f68

build:
  number: 0
  entry_points:
    - pythonfmu3 = pythonfmu3.__main__:cli_main

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
    - pyfmi
    - numpy
  commands:
    - pytest --pyargs pythonfmu3.tests
  imports:
    - pythonfmu3

about:
  home: https://github.com/StephenSmith25/PythonFMU3
  summary: A lightweight framework that enables the packaging of Python3.x code as co-simulation FMUs following version 3.0.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/StephenSmith25/PythonFMU3

extra:
  recipe-maintainers:
    - StephenSmith25
